apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      name: ftps
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: s-ftps
        imagePullPolicy: Never
        ports:
        - name: ftps-connection
          containerPort: 21
          containerPort: 20
        - name: passv-mode
          containerPort: 21000
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  name: ftps
spec:
  selector:
    app: ftps
  type: LoadBalancer
  ports:
  - name: ftp20
    port: 20
    targetPort: 20
  - name: ftps-21
    port: 21
    targetPort: 21
  - name: ftps-21000
    port: 21000