apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: s-wordpress
        ports:
        - containerPort: 5050
        imagePullPolicy: Never
        env:
          - name: MYSQL_IP
            value: 10.106.5.36
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  name: wordpress
  labels:
    app: wordpress
spec:
  type: LoadBalancer
  ports:
  - name: wordpress
    port: 5050
    targetPort: 5050
  selector:
    app: wordpress