  
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: mysql-pv-claim
#   namespace: default
#   labels:
#     app: mysql-pv-claim
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 500Mi
# ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: s-mysql
        imagePullPolicy: Never
        ports:
        - containerPort: 3306
          name: mysql
      #   volumeMounts:
      #     - mountPath: /var/lib/mysql
      #       name: mysql-persistent-volume
      # volumes:
      #  - name: mysql-persistent-volume
      #    persistentVolumeClaim:
      #     claimName: mysql-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  type: ClusterIP
  clusterIP: 10.106.5.36
  ports:
    - port: 3306
  selector:
    app: mysql